{% set name = "libtree-sitter" %}
{% set version = "0.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tree-sitter/tree-sitter/archive/v{{ version }}.tar.gz
  sha256: 30ea382bdaea8fc71e3d52850da509398f56d77b7c41e3494da46a1158d37b86
build:
  number: 0

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - cmake  # [win]
    - make  # [unix]
    - ninja  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libtree-sitter${SHLIB_EXT}  # [unix]

about:
  home: https://tree-sitter.github.io/
  license: MIT
  license_file: LICENSE
  summary: Shared C library for tree-sitter
  dev_url: https://github.com/tree-sitter/tree-sitter

extra:
  recipe-maintainers:
    - danielnachun
