{% set name = "libtree-sitter" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tree-sitter/tree-sitter/archive/v{{ version }}.tar.gz
  sha256: 1cc0c832c6cc3d04f0b702247fac3dac45f958b0ee1f946619b7ae7b67258060

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake  # [win]
    - make  # [unix]
    - ninja  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libtree-sitter${SHLIB_EXT}  # [unix]

about:
  home: https://tree-sitter.github.io/
  license: MIT
  license_file: LICENSE
  summary: Shared C library for tree-sitter
  dev_url: https://github.com/tree-sitter/tree-sitter

extra:
  recipe-maintainers:
    - danielnachun
