{% set name = "libtree-sitter" %}
{% set version = "0.20.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tree-sitter/tree-sitter/archive/v{{ version }}.tar.gz
  sha256: 9b2fd489a7281e3a7e5e7cbbf3a974e5a6a115889ae65676d61b79bdae96464e

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake  # [win]
    - make  # [unix]
    - ninja  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libtree-sitter${SHLIB_EXT}  # [unix]

about:
  home: https://tree-sitter.github.io/
  license: MIT
  license_file: LICENSE
  summary: Shared C library for tree-sitter
  dev_url: https://github.com/tree-sitter/tree-sitter

extra:
  recipe-maintainers:
    - danielnachun
