{% set name = "libtree-sitter" %}
{% set version = "0.20.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tree-sitter/tree-sitter/archive/v{{ version }}.tar.gz
  sha256: 6181ede0b7470bfca37e293e7d5dc1d16469b9485d13f13a605baec4a8b1f791

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/libtree-sitter${SHLIB_EXT}

about:
  home: https://tree-sitter.github.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Shared C library for tree-sitter
  dev_url: https://github.com/tree-sitter/tree-sitter

extra:
  recipe-maintainers:
    - danielnachun
