{% set name = "libtree-sitter" %}
{% set version = "0.24.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tree-sitter/tree-sitter/archive/v{{ version }}.tar.gz
  sha256: 199da041ac7ef62bccdda9b7bec28aafa073f7eea2677680aa7992d503c9cc64
build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libtree-sitter', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - cmake  # [win]
    - make  # [unix]
    - ninja  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libtree-sitter${SHLIB_EXT}  # [unix]

about:
  home: https://tree-sitter.github.io/
  license: MIT
  license_file: LICENSE
  summary: Shared C library for tree-sitter
  dev_url: https://github.com/tree-sitter/tree-sitter

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
