context:
  version: "0.25.2"

package:
  name: libtree-sitter
  version: ${{ version }}

source:
  url: https://github.com/tree-sitter/tree-sitter/archive/v${{ version }}.tar.gz
  sha256: 26791f69182192fef179cd58501c3226011158823557a86fe42682cb4a138523

build:
  number: 0

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('c') }}
    - if: win
      then: cmake
    - if: unix
      then: make
    - if: win
      then: ninja
  run_exports:
    - ${{ pin_subpackage('libtree-sitter', upper_bound='x.x') }}

tests:
  - script:
      - if: unix
        then: test -f ${PREFIX}/lib/libtree-sitter${SHLIB_EXT}

about:
  license: MIT
  license_file: LICENSE
  summary: Shared C library for tree-sitter
  homepage: https://tree-sitter.github.io/
  repository: https://github.com/tree-sitter/tree-sitter

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
